accent = "#ff7edb"
cursor = "#f97e72"
foreground = "#ffffff"
background = "#171520"
selection_foreground = "#ffffff"
selection_background = "#614D85"

color0 = "#262335"
color1 = "#fe4450"
color2 = "#72f1b8"
color3 = "#f3e70f"
color4 = "#03edf9"
color5 = "#ff7edb"
color6 = "#03edf9"
color7 = "#ffffff"
color8 = "#495495"
color9 = "#fe4450"
color10 = "#72f1b8"
color11 = "#fede5d"
color12 = "#03edf9"
color13 = "#ff7edb"
color14 = "#03edf9"
color15 = "#ffffff"
